//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.HealthInsurance.ViewModels.VM;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace MedRec.HealthInsurance.Views.Pages;
public partial class HealthInsurancePage
{
    [Inject] public HealthInsuranceCatalogVM Model { get; set; }
    [Parameter] public EventCallback<(Guid Id, string Name)> OnHealthCompanySelected { get; set; }
    [Parameter] public int MaxPageButton { get; set; } = 9;
    private string footerMessage;
    private void OnMessageFooterChange(string title)
    {
        footerMessage = title;
    }

    private async void SelectedHealthCompany((Guid id, string name) selectedCompany)
    {
        await OnHealthCompanySelected.InvokeAsync((selectedCompany.id, selectedCompany.name));
    }

    ErrorBoundary ErrorBoundaryRef;

    void Recover()
    {
        ErrorBoundaryRef?.Recover();
    }
}