<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\2.ApplicationBusinessObjects\MedRec.MedicalVisit.BusinessObjects\MedRec.MedicalVisit.BusinessObjects.csproj" />
    <ProjectReference Include="..\..\2.ApplicationBusinessObjects\MedRec.Patients.BusinessObjects\MedRec.Patients.BusinessObjects.csproj" />
  </ItemGroup>

</Project>
