//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.CommonComponents.Views;
using MedRec.Entity.POCOEntities;
using MedRec.MedicalVisit.ViewModels.VM;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MedRec.MedicalVisit.Views.Components;
public partial class CreateMedicalVisitComponent
{
    [Inject] private NavigationManager Navigation { get; set; }
    [Parameter] public CreateMedicalVisitVM VM { get; set; }
    [Parameter] public Guid PatientId { get; set; }
    [Parameter] public string PatientName { get; set; }
    [Parameter] public bool IsReadOnly { get; set; }

    private EditContext _editContext;
    private bool ShowModal;
    private string ModalTitle = "Mensaje del sistema";
    private ModalType ModalType = ModalType.MessageInfo;


    private CancellationTokenSource _cts;

    protected override void OnInitialized()
    {   
        VM.Model.PatientId = PatientId;
        _editContext = new EditContext(VM.Model);
        


        // Suscripción a eventos del ViewModel
        VM.OnShowMessage += () => ShowModalMessage("Información", ModalType.MessageInfo);
        VM.OnShowWarning += () => ShowModalMessage("Advertencia", ModalType.MessageWarning);
        VM.OnShowError += () => ShowModalMessage("Error", ModalType.MessageError);
        VM.OnShowConcurrencyError += () => ShowModalMessage("Conflicto de concurrencia", ModalType.MessageError);
        VM.OnMedicalVisitAdded += StateHasChanged;
    }

    private void HandleButtonClick()
    {
        // Lógica para ejecutar al hacer clic en el botón
        Navigation.NavigateTo($"/medical-visit/list/{PatientId}/{PatientName}");
    }
    public async Task AddVisit()
    {
        if (_editContext.Validate() == true)
        {
            _cts?.Dispose();
            _cts = new CancellationTokenSource();
            await VM.AddMedicalVisitAsync(_cts.Token);
        }
        Navigation.NavigateTo($"/medical-visit/list/{PatientId}/{PatientName}", true);
    }
    private void ShowModalMessage(string title, ModalType type)
    {
        ModalTitle = title;
        ModalType = type;
        ShowModal = true;
        InvokeAsync(StateHasChanged);
    }

    private void CloseModal()
    {
        ShowModal = false;
    }
}