//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.CommonComponents.Views;
using MedRec.MedicalVisit.ViewModels.Models;
using MedRec.MedicalVisit.ViewModels.VM;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;

namespace MedRec.MedicalVisit.Views.Components;
public partial class CreateMedicalVisitComponent
{
    [Inject] private NavigationManager Navigation { get; set; }
    [Parameter] public CreateVisitVMOrchestrator VM { get; set; }
    [Parameter] public Guid PatientId { get; set; }
    [Parameter] public Guid? VisitId { get; set; }
    [Parameter] public bool CloneNow { get; set; } = false;

    private EditContext _editContext;
    private string _modalTitle = "Mensaje del sistema";
    private ModalType _modalType = ModalType.MessageInfo;
    private bool _showAcceptButton = false;
    private bool _showCancelButton = false;
    private bool _isConfirmationModal = false;
    private bool _showModal;

    private bool isLoading = false;

    private CreateMedicalVisitModel _originalModel;
    private bool _navigateAfterClose = false;
    private string _navigationUrl = "/";
    private string _modalMessage = string.Empty;
    private TaskCompletionSource<bool> _saveConfirmationTcs;
    private CancellationTokenSource _cts;

    private void SetLoading(bool loading)
    {
        isLoading = loading;
        InvokeAsync(StateHasChanged);
    }
    // ----------------------------------------------------------------------
    // CAMBIO 1: Inicializamos el EditContext y suscribimos eventos del ViewModel.
    // Esto permite mantener el enlace de validación y responder a mensajes.
    // ----------------------------------------------------------------------
    protected override void OnInitialized()
    {
        VM.Model.PatientId = PatientId;
        _editContext = new EditContext(VM.Model);

        // Suscripción a eventos del ViewModel
        VM.OnShowMessage += () => ShowModalMessage("Información", ModalType.MessageInfo);
        VM.OnShowWarning += () => ShowModalMessage("Advertencia", ModalType.MessageWarning);
        VM.OnShowError += () => ShowModalMessage("Error", ModalType.MessageError);
        VM.OnShowConcurrencyError += () => ShowModalMessage("Conflicto de concurrencia", ModalType.MessageError);
        VM.OnMedicalVisitAdded += StateHasChanged;
    }

    // ----------------------------------------------------------------------
    // NUEVO: Asegura que el EditContext refleje el VM.Model actual.
    // Si VM.Model se reemplaza (por ejemplo al cargar datos) recreamos el EditContext
    // para que la validación use el objeto correcto.
    // ----------------------------------------------------------------------
    protected override void OnParametersSet()
    {
        base.OnParametersSet();

        if (VM is not null)
        {
            if (_editContext == null || !ReferenceEquals(_editContext.Model, VM.Model))
            {
                _editContext = new EditContext(VM.Model);
                InvokeAsync(StateHasChanged);
            }
        }
    }

    // ----------------------------------------------------------------------
    // CAMBIO 2: Método que muestra un modal y luego navega al cerrar.
    // Se usa cuando el guardado fue exitoso.
    // ----------------------------------------------------------------------
    private void ShowModalMessageAndNavigate(string title, ModalType type, string navigationUrl,
        bool showAcceptButton = true, bool showCancelButton = false)
    {
        _modalTitle = title;
        _modalType = type;
        _showModal = true;
        _navigateAfterClose = true;
        _navigationUrl = navigationUrl;
        _modalMessage = VM.InformationMessage;
        InvokeAsync(StateHasChanged);
    }

    // ----------------------------------------------------------------------
    // CAMBIO 3: Método para mostrar modal sin navegar.
    // Se usa para errores o advertencias.
    // ----------------------------------------------------------------------
    private void ShowModalMessage(string title, ModalType type,
        bool showAcceptButton = true, bool showCancelButton = false)
    {
        _modalTitle = title;
        _modalType = type;
        _showModal = true;
        _showAcceptButton = showAcceptButton;
        _showCancelButton = showCancelButton;
        _navigateAfterClose = false;
        _modalMessage = VM.InformationMessage;
        InvokeAsync(StateHasChanged);
    }

    private string CreateUrl()
    {
        var nombreCodificado = System.Web.HttpUtility.UrlEncode($"{VM.Model.FullName}");
        var fechaCodificada = VM.Model.DateOfBirth.ToString("yyyy-MM-dd");
        return $"/medical-visit/list?id={PatientId}&nombre={nombreCodificado}&fechaNac={fechaCodificada}";
    }

    private void HandleButtonClick() => Navigation.NavigateTo(CreateUrl(), true);

    // ----------------------------------------------------------------------
    // CAMBIO 4: SaveChanged con manejo seguro de tokens y modal de éxito.
    // Se limpian correctamente recursos y se reinicia el modelo si fue guardado.
    // ----------------------------------------------------------------------
    public async Task SaveChanged()
    {
        if (_editContext.Validate() == true)
        {
            _cts?.Dispose();
            _cts = new CancellationTokenSource();

            try
            {
                SetLoading(true);
                await VM.AddMedicalVisitAsync(_cts.Token);
                SetLoading(false);
                if (string.IsNullOrEmpty(VM.InformationMessage))
                {
                    VM.InformationMessage = "LOS DATOS FUERON GUARDADOS SATISFACTORIAMENTE";
                    _isConfirmationModal = false;

                    ShowModalMessageAndNavigate("CONFIRMACIÓN DE GUARDADO", ModalType.MessageSuccess, CreateUrl());

                    // Reiniciar modelo y EditContext para limpiar formulario
                    VM.Model = new CreateMedicalVisitModel();
                    _editContext = new EditContext(VM.Model);
                }
            }
            catch (InvalidOperationException ex)
            {
                VM.InformationMessage = ex.Message;
                _isConfirmationModal = false;
                ShowModalMessage("ERROR CRÍTICO", ModalType.MessageError);
            }
        }
    }

    private void OnAcceptSave()
    {
        if (_isConfirmationModal && _saveConfirmationTcs != null)
        {
            _saveConfirmationTcs.SetResult(true);
            _saveConfirmationTcs = null;
            _isConfirmationModal = false;
            _showModal = false;
            return;
        }

        CloseModal();
    }

    // ----------------------------------------------------------------------
    // CAMBIO 5: CloseModal mejora la limpieza del componente.
    //  - Cancela operaciones pendientes.
    //  - Desuscribe los eventos del ViewModel.
    //  - Libera recursos (Dispose).
    //  - Navega si es necesario.
    // ----------------------------------------------------------------------
    private void CloseModal()
    {
        _showModal = false;

        // Cancelar operaciones pendientes
        _cts?.Cancel();
        _cts?.Dispose();
        _cts = null;

        // Desuscribirse de eventos para liberar el ViewModel
        if (VM is not null)
        {
            VM.OnShowMessage -= () => ShowModalMessage("Información", ModalType.MessageInfo);
            VM.OnShowWarning -= () => ShowModalMessage("Advertencia", ModalType.MessageWarning);
            VM.OnShowError -= () => ShowModalMessage("Error", ModalType.MessageError);
            VM.OnShowConcurrencyError -= () => ShowModalMessage("Conflicto de concurrencia", ModalType.MessageError);
            VM.OnMedicalVisitAdded -= StateHasChanged;
        }

        // Liberar recursos del ViewModel si implementa IDisposable
        if (VM is IDisposable disposableVM)
            disposableVM.Dispose();

        // Finalmente, navegar si corresponde
        if (_navigateAfterClose)
        {
            _navigateAfterClose = false;
            Navigation.NavigateTo(_navigationUrl, forceLoad: true); // Fuerza recarga completa
        }
    }

    // ----------------------------------------------------------------------
    // CAMBIO 6: Implementamos IDisposable para liberar recursos
    // cuando el componente se destruye (por ejemplo, al navegar).
    // ----------------------------------------------------------------------
    public void Dispose()
    {
        CloseModal(); // Reutilizamos la lógica existente para limpiar todo
    }
}
