//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.Entity.DTOs;
using MedRec.Entity.Enums;
using MedRec.Entity.Extensions;
using MedRec.Entity.POCOEntities;
using MedRec.MedicalVisit.ViewModels.Models;
using MedRec.MedicalVisit.ViewModels.VM;
using Microsoft.AspNetCore.Components;

namespace MedRec.MedicalVisit.Views.Components;
public partial class MedicalVisitHistoryComponent
{
    #region Inyeccion de dependencias
    [Inject] private NavigationManager Navigation { get; set; }
    #endregion

    #region Parámetros
    [Parameter] public MedicalVisitVM VM { get; set; }
    [Parameter] public EventCallback<MedicalVisitModel> OnVisitSelected { get; set; }
    [Parameter] public Guid PatientId { get; set; }
    [Parameter] public string PatientName { get; set; }
    [Parameter] public DateTime DateOfBirth { get; set; }
    #endregion

    #region Campos
    private CancellationTokenSource _debounceCts;
    private PaginationDto _paginationDto = new(1, 100);
    private List<SelectOptionDto> _visitReasonOptions = new();
    #endregion

    #region Propiedades
    private string TextFilter
    {
        get => _paginationDto.FilterOne;
        set
        {
            if (_paginationDto.FilterOne != value)
            {
                _paginationDto.FilterOne = value;
                // Llamar al método de debounce cada vez que el valor cambia
                _ = OnSearchTermChanged(value);
            }
        }
    }
    #endregion
    protected override async Task OnInitializedAsync()
    {
        _visitReasonOptions = Enum.GetValues<VisitReason>()
        .Select(r => new SelectOptionDto
        {
            Value = r.ToString(),
            Text = r.GetDescription()
        })
        .ToList();

        await LoadVisits();
    }
    private void OnButtonClick()
    {
        var nombreCodificado = System.Web.HttpUtility.UrlEncode(PatientName);
        var fechaCodificada = DateOfBirth.ToString("yyyy-MM-dd");
        var url = $"/medical-visit/create?id={PatientId}&nombre={nombreCodificado}&fechaNac={fechaCodificada}";

        Navigation.NavigateTo(url, true);
    }

    private async Task OnSearchTermChanged(string searchTerm)
    {
        // Cancelar la búsqueda anterior si existe
        _debounceCts?.Cancel();
        _debounceCts = new CancellationTokenSource();

        // Solo buscar si hay más de 2 caracteres o está vacío
        if (searchTerm.Length > 2 || searchTerm.Length == 0)
        {
            try
            {
                // Esperar 600ms antes de buscar
                await Task.Delay(600, _debounceCts.Token);
                _paginationDto.CurrentPage = 1;
                await LoadVisits();
            }
            catch (TaskCanceledException)
            {
                // Ignorar si se cancela por nueva entrada
            }
        }
    }
    private async Task LoadVisits()
    {
        await VM.LoadVisitsAsync(PatientId, _paginationDto);
        StateHasChanged();
    }
}