//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.CommonComponents.Views;
using MedRec.MedicalVisit.ViewModels.Models;
using MedRec.MedicalVisit.ViewModels.VM;
using MedRec.Shared.DTOs;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;

namespace MedRec.MedicalVisit.Views.Components;
public partial class UpdateMedicalVisitComponent
{
    [Inject] private NavigationManager Navigation { get; set; }
    [Parameter] public UpdateMedicalVisitVM VM { get; set; }
    [Parameter] public Guid PatientId { get; set; }
    [Parameter] public Guid? VisitId { get; set; }
    [Parameter] public bool IsReadOnly { get; set; }
    [Parameter] public bool IsEditMode { get; set; }
    [Parameter] public bool CloneNow { get; set; } = false;

    private EditContext _editContext;
    private UpdateMedicalVisitModel _originalModel;
    private CancellationTokenSource _cts;

    private Dictionary<string, bool> _conflictedFields = new();

    private bool HasConflict(string propertyName)
        => _conflictedFields.TryGetValue(propertyName, out bool val) && val;


    // Estado del modal
    private string _modalTitle = "Mensaje del sistema";
    private string _modalMessage = string.Empty;
    private ModalType _modalType = ModalType.MessageInfo;
    private bool _showModal = false;
    private bool _isConfirmationModal = false;
    private bool _showAcceptButton = false;
    private bool _showCancelButton = false;
    
    private bool isLoading = false;
    
    // Nueva variable para manejar navegación luego de cerrar modal (CAMBIO)
    private bool _navigateAfterClose = false;
    private string _navigationUrl = "/";

    // TaskCompletionSource para esperar confirmación del usuario antes de guardar (CAMBIO)
    private TaskCompletionSource<bool> _saveConfirmationTcs;

    // Nueva propiedad calculada para detectar cambios (CAMBIO)
    private bool HasChanges => DeepEquals(_originalModel, VM.Model);

    private void SetLoading(bool loading)
    {
        isLoading = loading;
        InvokeAsync(StateHasChanged);
    }

    protected override void OnInitialized()
    {
        VM.Model.PatientId = PatientId;
        _editContext = new EditContext(VM.Model);

        // Suscripción de eventos con métodos unificados (CAMBIO)
        VM.OnShowMessage += () => ShowModalMessage("Informacion", ModalType.MessageInfo);
        VM.OnShowWarning += () => ShowModalMessage("Advertencia", ModalType.MessageWarning);
        VM.OnShowError += () => ShowModalMessage("Error", ModalType.MessageError);
        VM.OnShowConcurrencyError += () => ShowModalMessage("Conflicto de concurrencia", ModalType.MessageError);
        VM.OnFinnishOperation += StateHasChanged;
    }
    protected override void OnParametersSet()
    {
        base.OnParametersSet();

        if (VM is not null)
        {
            if (_editContext == null || !ReferenceEquals(_editContext.Model, VM.Model))
            {
                _editContext = new EditContext(VM.Model);
                InvokeAsync(StateHasChanged);
            }
        }
    }

    private async Task SaveChanged()
    {
        if (!_editContext.Validate())
            return;

        _cts?.Dispose();
        _cts = new CancellationTokenSource();

        // Mostrar confirmación antes de guardar (CAMBIO)
        VM.InformationMessage = "¿SEGURO DESEA MODIFICAR LOS DATOS DE LA VISITA?";
        _isConfirmationModal = true;
        _showAcceptButton = true;
        _showCancelButton = true;
        ShowModalMessage("CONFIRMACIÓN DE ACTUALIZACIÓN", ModalType.MessageWarning, true, true);

        // Esperamos la respuesta del usuario (CAMBIO)
        _saveConfirmationTcs = new TaskCompletionSource<bool>();
        
        
        bool confirmed = await _saveConfirmationTcs.Task;
       

        _showModal = false;
        if (!confirmed)
            return;

        await Task.Delay(50); // margen para evitar conflicto UI
           
        try
        {
            //_originalModel = VM.Model.Clone();

            SetLoading(true);
            await VM.UpdateMedicalVisitAsync(_cts.Token);
            SetLoading(false);

            if (VM.ConcurrencyError?.Count > 0)
            {
                _conflictedFields.Clear();

                foreach (var err in VM.ConcurrencyError)
                    _conflictedFields[err.PropertyName] = true;

                await InvokeAsync(StateHasChanged);
                return;
            }

            if (!string.IsNullOrEmpty(VM.InformationMessage))
            {
                _originalModel = VM.Model.Clone();
                await InvokeAsync(StateHasChanged);
            }
            else 
            { 
                VM.InformationMessage = "LOS DATOS FUERON ACTUALIZADOS SATISFACTORIAMENTE";
                _isConfirmationModal = false;
                _showAcceptButton = true;
                _showCancelButton = false;
                
                var url = CreateUrl();

                ShowModalMessageAndNavigate("CONFIRMACIÓN DE ACTUALIZACION", ModalType.MessageSuccess, CreateUrl());

                // Reiniciar modelo y EditContext para limpiar formulario
                VM.Model = new UpdateMedicalVisitModel();
                _editContext = new EditContext(VM.Model);

            }
        }
        catch (InvalidOperationException ex)
        {
            VM.InformationMessage = ex.Message;
            _isConfirmationModal = false;
            ShowModalMessage("ERROR CRÍTICO", ModalType.MessageError);
        }        
    }

    // Metodo seguro de comparación profunda de modelos (CAMBIO)
    private bool DeepEquals(UpdateMedicalVisitModel a, UpdateMedicalVisitModel b)
    {
        if (a == null || b == null) return a == b;

        // Esto es una función local para comparar si dos cadenas son iguales, evitando error si alguna es null.
        bool Same(string s1, string s2) =>
            string.Equals(s1?.Trim(), s2?.Trim(), StringComparison.OrdinalIgnoreCase);

        var equal = Same(a.Reason, b.Reason)
            && Same(a.Diagnosis, b.Diagnosis)
            && Same(a.Treatment, b.Treatment)
            && Same(a.Notes, b.Notes)
            && a.SystolicPressure == b.SystolicPressure
            && a.DiastolicPressure == b.DiastolicPressure
            && a.PulsePerMinute == b.PulsePerMinute
            && a.Temperature == b.Temperature;

        return equal;
    }

    // Muestra modal informativo (igual que antes, pero ahora resetea flags de navegación)
    private void ShowModalMessage(string title, ModalType type, bool showAcceptButton = true, bool showCancelButton = false)
    {
        _modalTitle = title;
        _modalType = type;
        _modalMessage = VM.InformationMessage;
        _showModal = true;
        _showAcceptButton = showAcceptButton;
        _showCancelButton = showCancelButton;
        _navigateAfterClose = false;
        InvokeAsync(StateHasChanged);
    }

    // Muestra modal y marca que debe navegar al cerrarse (CAMBIO)
    private void ShowModalMessageAndNavigate(string title, ModalType type, string navigationUrl, bool showAcceptButton = true, bool showCancelButton = false)
    {
        _modalTitle = title;
        _modalType = type;
        _modalMessage = VM.InformationMessage;
        _showModal = true;
        _navigateAfterClose = true;
        _navigationUrl = navigationUrl;
        _showAcceptButton = showAcceptButton;
        _showCancelButton = showCancelButton;
        InvokeAsync(StateHasChanged);
    }

    // Botón Aceptar del modal (CAMBIO: maneja confirmación y cierra)
    private void OnAcceptSave()
    {
        if (_isConfirmationModal && _saveConfirmationTcs != null)
        {
            _saveConfirmationTcs.SetResult(true);
            _saveConfirmationTcs = null;
            _isConfirmationModal = false;
            _showModal = false;
            return;
        }

        CloseModal();
    }

    private void CloseModal()
    {
        _showModal = false;
        _cts?.Cancel();
        _cts?.Dispose();
        _cts = null;

        // De suscribimos eventos (CAMBIO)
        if (VM is not null)
        {
            VM.OnShowMessage -= () => ShowModalMessage("Informacion", ModalType.MessageInfo);
            VM.OnShowWarning -= () => ShowModalMessage("Advertencia", ModalType.MessageWarning);
            VM.OnShowError -= () => ShowModalMessage("Error", ModalType.MessageError);
            VM.OnShowConcurrencyError -= () => ShowModalMessage("Conflicto de concurrencia", ModalType.MessageError);
            VM.OnFinnishOperation -= StateHasChanged;
        }

        // Si el VM implementa IDisposable lo liberamos (CAMBIO)
        if (VM is IDisposable disposableVM)
            disposableVM.Dispose();

        // Navegamos solo después de cerrar modal (CAMBIO)
        if (_navigateAfterClose)
        {
            _navigateAfterClose = false;
            Navigation.NavigateTo(_navigationUrl, forceLoad: true);
        }
    }

    private string CreateUrl()
    {
        var nombreCodificado = System.Web.HttpUtility.UrlEncode(VM.Model.FullName ?? string.Empty);
        var fechaCodificada = VM.Model.DateOfBirth.ToString("yyyy-MM-dd");
        return $"/medical-visit/list?id={PatientId}&nombre={nombreCodificado}&fechaNac={fechaCodificada}";
    }

    private void HandleButtonClick() => Navigation.NavigateTo(CreateUrl(), true);
}