<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedRec.CommonComponents.Views\MedRec.CommonComponents.Views.csproj" />
    <ProjectReference Include="..\MedRec.HealthInsurance.Views\MedRec.HealthInsurance.Views.csproj" />
    <ProjectReference Include="..\MedRec.Patients.ViewModels\MedRec.Patients.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\CreatePatientMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CreatePatientMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\CreatePatientMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>CreatePatientMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
