//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRec.MedicalAppointments.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WeeklyScheduleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeeklyScheduleMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedRec.MedicalAppointments.Views.Resources.WeeklyScheduleMessages", typeof(WeeklyScheduleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASIGNAR TURNO.
        /// </summary>
        internal static string AssignAppointmentTitle {
            get {
                return ResourceManager.GetString("AssignAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TURNO ASIGNADO.
        /// </summary>
        internal static string AssignedAppointmentTitle {
            get {
                return ResourceManager.GetString("AssignedAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NCELAR TURNO.
        /// </summary>
        internal static string CancelAppointmentButton {
            get {
                return ResourceManager.GetString("CancelAppointmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CNACELAR.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR MOVER.
        /// </summary>
        internal static string CancelMoveButton {
            get {
                return ResourceManager.GetString("CancelMoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOVER A OTRA FECHA.
        /// </summary>
        internal static string MoveAppointmentButton {
            get {
                return ResourceManager.GetString("MoveAppointmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PACIENTE.
        /// </summary>
        internal static string PatientPlaceholder {
            get {
                return ResourceManager.GetString("PatientPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECTOR DE PACIENTE.
        /// </summary>
        internal static string PatientSelectorTitle {
            get {
                return ResourceManager.GetString("PatientSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTIVO.
        /// </summary>
        internal static string ReasonPlaceholder {
            get {
                return ResourceManager.GetString("ReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REASIGNAR PACIENTE.
        /// </summary>
        internal static string ReassignPatientButton {
            get {
                return ResourceManager.GetString("ReassignPatientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEMANA:.
        /// </summary>
        internal static string WeekLabel {
            get {
                return ResourceManager.GetString("WeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AGENDA MES DE:.
        /// </summary>
        internal static string WeeklyScheduleTitle {
            get {
                return ResourceManager.GetString("WeeklyScheduleTitle", resourceCulture);
            }
        }
    }
}
