//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;

namespace MedRec.CommonComponents.Views.Components;
public partial class MdMessageModal
{

    /* ===========================
    PARAMETROS
    ============================ */

    [Parameter] public bool Visible { get; set; }
    [Parameter] public bool CloseOnOverlayClick { get; set; } = true;
    [Parameter] public EventCallback<bool> VisibleChanged { get; set; }

    /// Tipo del modal: "info", "warning", "error"
    [Parameter] public ModalType Type { get; set; } = ModalType.MessageInfo;

    [Parameter] public string Title { get; set; } = "Mensaje";
    [Parameter] public string Message { get; set; }
    [Parameter] public RenderFragment Body { get; set; }

    // Botones
    [Parameter] public bool ShowOk { get; set; } = true;
    [Parameter] public bool ShowCancel { get; set; } = false;
    [Parameter] public bool ShowRetry { get; set; } = false;
    [Parameter] public bool ShowDelete { get; set; } = false;

    // Eventos
    [Parameter] public EventCallback OnOk { get; set; }
    [Parameter] public EventCallback OnCancel { get; set; }
    [Parameter] public EventCallback OnRetry { get; set; }
    [Parameter] public EventCallback OnDelete { get; set; }

    private bool IsLargeModal => Type == ModalType.LargeContent;
    /* ===========================
    ÍCONOS SVG LUCIDE
    ============================ */
    private RenderFragment IconSvg => builder =>
    {
        var seq = 0;

        if (Type == ModalType.MessageError)
        {
            builder.OpenElement(seq++, "svg");
            builder.AddAttribute(seq++, "class", "modal-icon error");
            builder.AddAttribute(seq++, "viewBox", "0 0 24 24");
            builder.AddAttribute(seq++, "stroke-linecap", "round");
            builder.AddAttribute(seq++, "stroke-linejoin", "round");
            builder.AddAttribute(seq++, "stroke-width", "2");
            builder.AddAttribute(seq++, "width", "42");
            builder.AddAttribute(seq++, "height", "42");
            builder.AddMarkupContent(seq++,
            @"<circle cx='12' cy='12' r='10' />
               <path d='m15 9-6 6' />
                <path d='m9 9 6 6' />");
            builder.CloseElement();
        }
        else if (Type == ModalType.MessageWarning)
        {
            builder.OpenElement(seq++, "svg");
            builder.AddAttribute(seq++, "class", "modal-icon warning");
            builder.AddAttribute(seq++, "viewBox", "0 0 24 24");
            builder.AddAttribute(seq++, "stroke-linecap", "round");
            builder.AddAttribute(seq++, "stroke-linejoin", "round");
            builder.AddAttribute(seq++, "stroke-width", "2");
            builder.AddAttribute(seq++, "width", "42");
            builder.AddAttribute(seq++, "height", "42");
            builder.AddMarkupContent(seq++,
            @"<path d='m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3'/>
              <path d='M12 9v4'/>
              <path d='M12 17h.01'/>");
            builder.CloseElement();
        }
        else if (Type == ModalType.MessageInfo)
        {
            builder.OpenElement(seq++, "svg");
            builder.AddAttribute(seq++, "class", "modal-icon info");
            builder.AddAttribute(seq++, "viewBox", "0 0 24 24");
            builder.AddAttribute(seq++, "stroke-linecap", "round");
            builder.AddAttribute(seq++, "stroke-linejoin", "round");
            builder.AddAttribute(seq++, "stroke-width", "2");
            builder.AddAttribute(seq++, "width", "42");
            builder.AddAttribute(seq++, "height", "42");
            builder.AddMarkupContent(seq++,
            @"<circle cx='12' cy='12' r='10'/>
              <path d='M12 16v-4'/>
              <path d='M12 8h.01'/>");
            builder.CloseElement();
        }
        else if (Type == ModalType.MessageDanger)
        {
            builder.OpenElement(seq++, "svg");
            builder.AddAttribute(seq++, "class", "modal-icon error");
            builder.AddAttribute(seq++, "viewBox", "0 0 24 24");
            builder.AddAttribute(seq++, "stroke-linecap", "round");
            builder.AddAttribute(seq++, "stroke-linejoin", "round");
            builder.AddAttribute(seq++, "stroke-width", "2");
            builder.AddAttribute(seq++, "width", "42");
            builder.AddAttribute(seq++, "height", "42");
            builder.AddMarkupContent(seq++,
            @"<path d='m12.5 17-.5-1-.5 1h1z' />
              <path d='M15 22a1 1 0 0 0 1-1v-1a2 2 0 0 0 1.56-3.25 8 8 0 1 0-11.12 0A2 2 0 0 0 8 20v1a1 1 0 0 0 1 1z'/>
              <circle cx='15' cy='12' r='1'/>
              <circle cx='9' cy='12' r='1'/>");
            builder.CloseElement();
        }
        else if (Type == ModalType.MessageSuccess)
        {
            builder.OpenElement(seq++, "svg");
            builder.AddAttribute(seq++, "class", "modal-icon success");
            builder.AddAttribute(seq++, "viewBox", "0 0 24 24");
            builder.AddAttribute(seq++, "stroke-linecap", "round");
            builder.AddAttribute(seq++, "stroke-linejoin", "round");
            builder.AddAttribute(seq++, "stroke-width", "2");
            builder.AddAttribute(seq++, "width", "42");
            builder.AddAttribute(seq++, "height", "42");
            builder.AddMarkupContent(seq++,
            @"<path d='m9 10 2 2 4-4'/><rect width='20' height='14' x='2' y='3' rx='2'/><path d='M12 17v4'/><path d='M8 21h8'/>");
            builder.CloseElement();
        }
        else if (Type == ModalType.LargeContent)
        {

        }
    };

    /* ===========================
       ACCIONES
    ============================ */
    private async Task CloseModal()
    {
        Visible = false;
        await VisibleChanged.InvokeAsync(false);
    }

    private Task OnOverlayClick() => CloseModal();

    private async Task ClickOk()
    {
        if (OnOk.HasDelegate)
            await OnOk.InvokeAsync(null);
        await CloseModal();
    }

    private async Task ClickCancel()
    {
        if (OnCancel.HasDelegate)
            await OnCancel.InvokeAsync(null);
        await CloseModal();
    }

    private async Task ClickRetry()
    {
        if (OnRetry.HasDelegate)
            await OnRetry.InvokeAsync(null);
        await CloseModal();
    }

    private async Task ClickDelete()
    {
        if (OnDelete.HasDelegate)
            await OnDelete.InvokeAsync(null);
        await CloseModal();
    }
}