//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;

namespace MedRec.CommonComponents.Views.Components;
public partial class ModalComponent
{
    [Parameter] public RenderFragment ChildContent { get; set; }
    [Parameter] public bool Show { get; set; }
    [Parameter] public EventCallback<bool> ShowChanged { get; set; }
    [Parameter] public string Title { get; set; }
    [Parameter] public EventCallback Closing { get; set; }
    [Parameter] public ModalType Type { get; set; } = ModalType.MessageInfo;
    [Parameter] public bool CenterText { get; set; } = false;
    [Parameter] public bool ShowAcceptButton { get; set; } // NUEVA PROPIEDAD
    [Parameter] public EventCallback OnAccept { get; set; } // NUEVA PROPIEDAD
    [Parameter] public bool ShowCancelButton { get; set; } // NUEVA PROPIEDAD
    
    private bool IsLargeModal => Type == ModalType.LargeContent;

    private void Close()
    {
        Show = false;
        ShowChanged.InvokeAsync(Show);
        Closing.InvokeAsync();
    }
    private string GetModalClass()
    {
        return Type switch
        {
            ModalType.MessageSuccess => "my-modal-success",
            ModalType.MessageError => "my-modal-error",
            ModalType.MessageWarning => "my-modal-warning",
            ModalType.MessageInfo => "my-modal-info",
            _ => string.Empty
        };
    }

    private RenderFragment GetIcon() => builder =>
    {
        var iconMap = new Dictionary<ModalType, string>
    {
        { ModalType.MessageSuccess, "bi bi-check-circle-fill text-success" },
        { ModalType.MessageError,   "bi bi-x-circle-fill text-danger" },
        { ModalType.MessageWarning, "bi bi-exclamation-triangle-fill text-warning" },
        { ModalType.MessageInfo,    "bi bi-info-circle-fill text-primary" },
        { ModalType.LargeContent,   "" } // sin icono
    };

        if (iconMap.TryGetValue(Type, out var iconClass) && !string.IsNullOrWhiteSpace(iconClass))
        {
            builder.OpenElement(0, "i");
            builder.AddAttribute(1, "class", iconClass);
            builder.CloseElement();
            builder.AddContent(2, " "); // espacio
        }
    };
}