//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;

namespace MedRec.CommonComponents.Views.Components;
public partial class ModalComponent
{
    // Contenido y configuración básica
    [Parameter] public string Title { get; set; }
    [Parameter] public RenderFragment ChildContent { get; set; }
    [Parameter] public ModalType Type { get; set; } = ModalType.MessageInfo;
    [Parameter] public bool CenterText { get; set; } = false;

    // Visibilidad y control del modal
    [Parameter] public bool Show { get; set; }
    [Parameter] public EventCallback<bool> ShowChanged { get; set; }
    [Parameter] public EventCallback Closing { get; set; }
    [Parameter] public EventCallback<bool> OnExit { get; set; }

    // Botón de aceptar
    [Parameter] public bool ShowAcceptButton { get; set; }
    [Parameter] public string ButtonAcceptText { get; set; } = "ACEPTAR";
    [Parameter] public EventCallback OnAccept { get; set; }

    // Botón de cancelar
    [Parameter] public bool ShowCancelButton { get; set; }
    [Parameter] public string ButtonCancelText { get; set; } = "CANCELAR";

    // Estilo y comportamiento adicional
    [Parameter] public bool ActionDangerous { get; set; } = false;
    private bool IsLargeModal => Type == ModalType.LargeContent;
    private bool IsNormalModal => Type == ModalType.LargeContent;
    private void Close()
    {
        Show = false;
        ShowChanged.InvokeAsync(Show);
        Closing.InvokeAsync();
    }
    private string GetModalClass()
    {
        return Type switch
        {
            ModalType.MessageSuccess => "my-modal-success",
            ModalType.MessageError => "my-modal-error",
            ModalType.MessageWarning => "my-modal-warning",
            ModalType.MessageInfo => "my-modal-info",
            _ => string.Empty
        };
    }

    private RenderFragment GetIcon() => builder =>
    {
        var iconMap = new Dictionary<ModalType, string>
    {
        { ModalType.MessageSuccess, "bi bi-check-circle-fill text-success" },
        { ModalType.MessageError,   "bi bi-x-circle-fill text-danger" },
        { ModalType.MessageWarning, "bi bi-exclamation-triangle-fill text-warning" },
        { ModalType.MessageInfo,    "bi bi-info-circle-fill text-primary" },
        { ModalType.LargeContent,   "" } // sin icono
    };

        if (iconMap.TryGetValue(Type, out var iconClass) && !string.IsNullOrWhiteSpace(iconClass))
        {
            builder.OpenElement(0, "i");
            builder.AddAttribute(1, "class", iconClass);
            builder.CloseElement();
            builder.AddContent(2, " "); // espacio
        }
    };
}