//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;

namespace MedRec.CommonComponents.Views.Components;
public partial class PaginationComponent
{
    [Parameter] public int CurrentPage { get; set; }
    [Parameter] public int TotalPages { get; set; }
    [Parameter] public EventCallback<int> PageChanged { get; set; }

    [Parameter]
    public int MaxPageButton
    {
        set { maxPageButtons = value; }
        get { return maxPageButtons; }
    }

    private int maxPageButtons;

    private bool IsFirstGroup => CurrentPage <= maxPageButtons;
    private bool IsLastGroup => CurrentPage > TotalPages - maxPageButtons;

    private int StartPage
    {
        get
        {
            // Calcular el rango visible alrededor de la página actual
            int start = Math.Max(1, CurrentPage - maxPageButtons / 2);

            // Asegurarse de que el rango no exceda las páginas totales disponibles
            if (start + maxPageButtons - 1 > TotalPages)
            {
                start = Math.Max(1, TotalPages - maxPageButtons + 1);
            }

            return start;
        }
    }

    private int EndPage
    {
        get
        {
            // Calcular la última página a mostrar
            int end = Math.Min(TotalPages, StartPage + maxPageButtons - 1);
            return end;
        }
    }


    private async Task GoToPage(int page)
    {
        if (page < 1)
        {
            page = 1;
        }
        else if (page > TotalPages)
        {
            page = TotalPages;
        }

        if (page != CurrentPage)
        {
            await PageChanged.InvokeAsync(page);
        }
    }

    private async Task PreviousPage()
    {
        await GoToPage(CurrentPage - 1);
    }

    private async Task NextPage()
    {
        await GoToPage(CurrentPage + 1);
    }

    private async Task GoToPreviousGroup()
    {
        await GoToPage(CurrentPage - maxPageButtons - 1);
    }

    private async Task GoToNextGroup()
    {
        await GoToPage(CurrentPage + maxPageButtons + 1);
    }
}