//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRec.Patients.BusinessObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatientValidatorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientValidatorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedRec.Patients.BusinessObjects.Resources.PatientValidatorMessages", typeof(PatientValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento no puede ser en el futuro..
        /// </summary>
        internal static string BirthDate_NotInFuture {
            get {
                return ResourceManager.GetString("BirthDate_NotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento no puede ser igual o mayor a la fecha actual..
        /// </summary>
        internal static string BirthDate_NotNowOrFuture {
            get {
                return ResourceManager.GetString("BirthDate_NotNowOrFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de documento debe contener como máximo {0} dígitos..
        /// </summary>
        internal static string Document_MaxLength {
            get {
                return ResourceManager.GetString("Document_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de documento debe contener al menos {0} dígitos..
        /// </summary>
        internal static string Document_MinLength {
            get {
                return ResourceManager.GetString("Document_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de documento solo debe contener dígitos..
        /// </summary>
        internal static string Document_Numeric {
            get {
                return ResourceManager.GetString("Document_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de documento es requerido..
        /// </summary>
        internal static string Document_Required {
            get {
                return ResourceManager.GetString("Document_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ingresado no tiene un formato válido..
        /// </summary>
        internal static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe contener como máximo {0} caracteres..
        /// </summary>
        internal static string FirstName_MaxLength {
            get {
                return ResourceManager.GetString("FirstName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido..
        /// </summary>
        internal static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo número de tarjeta debe tener menos de 16 caracteres..
        /// </summary>
        internal static string HealthInsuraceCard_MaxLength {
            get {
                return ResourceManager.GetString("HealthInsuraceCard_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo número de socio debe tener menos de 20 caracteres..
        /// </summary>
        internal static string HealthInsuraceMember_MaxLength {
            get {
                return ResourceManager.GetString("HealthInsuraceMember_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo número de plan debe ser menor a 20 caracteres..
        /// </summary>
        internal static string HealthInsuranePlan_MaxLength {
            get {
                return ResourceManager.GetString("HealthInsuranePlan_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar el número de carnet de la obra social..
        /// </summary>
        internal static string HealtInsuranceCard_Required {
            get {
                return ResourceManager.GetString("HealtInsuranceCard_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador del paciente es requerido..
        /// </summary>
        internal static string Id_Required {
            get {
                return ResourceManager.GetString("Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido debe contener como máximo {0} caracteres..
        /// </summary>
        internal static string LastName_MaxLength {
            get {
                return ResourceManager.GetString("LastName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido es requerido..
        /// </summary>
        internal static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de teléfono debe contener como máximo {0}caracteres..
        /// </summary>
        internal static string Phone_MaxLength {
            get {
                return ResourceManager.GetString("Phone_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de teléfono debe contener al menos {0} caracteres..
        /// </summary>
        internal static string Phone_MinLength {
            get {
                return ResourceManager.GetString("Phone_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de teléfono es requerido..
        /// </summary>
        internal static string Phone_Required {
            get {
                return ResourceManager.GetString("Phone_Required", resourceCulture);
            }
        }
    }
}
