//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace MedRec_PatientMedicalVisit.Views.Pages;
public partial class CreateMedicalVisitPage
{
    [Parameter] public Guid PatientId { get; set; }
    [Parameter] public string PatientName { get; set; }
    private string footerMessage;

    private void OnMessageFooterChange(string title)
    {
        footerMessage = title;
    }
    ErrorBoundary ErrorBoundaryRef;

    void Recover()
    {
        ErrorBoundaryRef?.Recover();
    }
}