<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Validators\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\1.EnterpriseBusinessObjects\MedRec.Entity\MedRec.Entity.csproj" />
    <ProjectReference Include="..\MedRec.BusinessObjects\MedRec.BusinessObjects.csproj" />
  </ItemGroup>

</Project>
