//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRec.MedicalVisit.BusinessObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MedicalVisitValidatorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MedicalVisitValidatorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedRec.MedicalVisit.BusinessObjects.Resources.MedicalVisitValidatorMessages", typeof(MedicalVisitValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El diagnóstico no puede exceder los {0} caracteres..
        /// </summary>
        internal static string Diagnosis_MaxLength {
            get {
                return ResourceManager.GetString("Diagnosis_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La presión diastólica debe estar entre {0} y {1} mmHg..
        /// </summary>
        internal static string DiastolicPressure_OutOfRange {
            get {
                return ResourceManager.GetString("DiastolicPressure_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar notas para la visita médica..
        /// </summary>
        internal static string Note_Required {
            get {
                return ResourceManager.GetString("Note_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las notas no pueden exceder los {0} caracteres..
        /// </summary>
        internal static string Notes_MaxLength {
            get {
                return ResourceManager.GetString("Notes_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador del paciente es obligatorio..
        /// </summary>
        internal static string PatientId_Required {
            get {
                return ResourceManager.GetString("PatientId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pulso debe estar entre {0} y {1} latidos por minuto..
        /// </summary>
        internal static string Pulse_OutOfRange_General {
            get {
                return ResourceManager.GetString("Pulse_OutOfRange_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pulso debe estar entre {0} y {1} latidos por minuto (FC máxima esperada para {2} años: {3} lpm)..
        /// </summary>
        internal static string Pulse_OutOfRange_WithAge {
            get {
                return ResourceManager.GetString("Pulse_OutOfRange_WithAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El motivo de la visita no puede exceder los {0} caracteres..
        /// </summary>
        internal static string Reason_MaxLength {
            get {
                return ResourceManager.GetString("Reason_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El motivo de la visita es obligatorio..
        /// </summary>
        internal static string Reason_Required {
            get {
                return ResourceManager.GetString("Reason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La presión sistólica debe estar entre {0} y {1} mmHg..
        /// </summary>
        internal static string SystolicPressure_OutOfRange {
            get {
                return ResourceManager.GetString("SystolicPressure_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La temperatura debe estar entre {0}°C y {1}°C..
        /// </summary>
        internal static string Temperature_OutOfRange {
            get {
                return ResourceManager.GetString("Temperature_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tratamiento no puede exceder los {0} caracteres..
        /// </summary>
        internal static string Treatment_MaxLength {
            get {
                return ResourceManager.GetString("Treatment_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de la visita no puede ser futura..
        /// </summary>
        internal static string VisitDate_NotInFuture {
            get {
                return ResourceManager.GetString("VisitDate_NotInFuture", resourceCulture);
            }
        }
    }
}
