//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;

namespace MedRec.HomeComponent.Views.Pages;
public partial class PatientsDashboard
{
    public enum Action { Add, Edit, Delete }

    [Parameter] public EventCallback<Action> OnActionRequested { get; set; }

    private void OnBackPressed()
    {
        // Lógica al presionar volver, por ejemplo navegar atrás
        NavManager.NavigateTo("/");
    }
}