//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRec.MedicalVisit.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MedicalVisitMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MedicalVisitMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedRec.MedicalVisit.Views.Resources.MedicalVisitMessages", typeof(MedicalVisitMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIMPIAR.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        internal static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR VISITA MÉDICA.
        /// </summary>
        internal static string ButtonSaveMedicalVisit {
            get {
                return ResourceManager.GetString("ButtonSaveMedicalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VISITA MEDICA REGISTRADA SATISFACTORIAMENTE.
        /// </summary>
        internal static string CreateMedicalVisit {
            get {
                return ResourceManager.GetString("CreateMedicalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PACIENTE: {0}  -  edad {1} años.
        /// </summary>
        internal static string CreateMedicalVisitTitleTemplate {
            get {
                return ResourceManager.GetString("CreateMedicalVisitTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESULTADOS DE LABORATORIO.
        /// </summary>
        internal static string HeaderLabResults {
            get {
                return ResourceManager.GetString("HeaderLabResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMACIÓN DE LA VISITA MÉDICA.
        /// </summary>
        internal static string HeaderVisitInfo {
            get {
                return ResourceManager.GetString("HeaderVisitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ANÁLISIS.
        /// </summary>
        internal static string LabelAnalysis {
            get {
                return ResourceManager.GetString("LabelAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRESIÓN DIA. (mmHg).
        /// </summary>
        internal static string LabelDiastPress {
            get {
                return ResourceManager.GetString("LabelDiastPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PULSO (por minutos).
        /// </summary>
        internal static string LabelPulsePerMinute {
            get {
                return ResourceManager.GetString("LabelPulsePerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOTAS.
        /// </summary>
        internal static string LabelResultNotes {
            get {
                return ResourceManager.GetString("LabelResultNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR.
        /// </summary>
        internal static string LabelResultValue {
            get {
                return ResourceManager.GetString("LabelResultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRESIÓN SIS. (mmHg).
        /// </summary>
        internal static string LabelSystPress {
            get {
                return ResourceManager.GetString("LabelSystPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEMPERATURA (°C).
        /// </summary>
        internal static string LabelTemperature {
            get {
                return ResourceManager.GetString("LabelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA.
        /// </summary>
        internal static string LabelVisitDate {
            get {
                return ResourceManager.GetString("LabelVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIAGNÓSTICO.
        /// </summary>
        internal static string LabelVisitDiagnosis {
            get {
                return ResourceManager.GetString("LabelVisitDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOTAS.
        /// </summary>
        internal static string LabelVisitNotes {
            get {
                return ResourceManager.GetString("LabelVisitNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTIVO DE LA VISITA.
        /// </summary>
        internal static string LabelVisitReason {
            get {
                return ResourceManager.GetString("LabelVisitReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRATAMIENTO.
        /// </summary>
        internal static string LabelVisitTreatment {
            get {
                return ResourceManager.GetString("LabelVisitTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ÉXITO.
        /// </summary>
        internal static string ModalSuccessTitle {
            get {
                return ResourceManager.GetString("ModalSuccessTitle", resourceCulture);
            }
        }
    }
}
