//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.CommonComponents.Views;
using MedRec.HealthInsurance.ViewModels.VM;
using MedRec.HealthInsurance.Views.Resources;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;

namespace MedRec.HealthInsurance.Views.Components;
public partial class AddHealthInsuranceComponent : IDisposable
{
    bool CloseOnOverlayClick = true;
    bool ModalVisible;
    ModalType ModalType = ModalType.MessageInfo;
    string ModalTitle = "";
    string ModalMessage = "";
    RenderFragment? ModalBody;

    bool ShowOk = false;
    bool ShowCancel = true;
    bool ShowRetry = false;
    bool ShowDelete = false;
    public bool Validate() => _editContext.Validate();
    private CreateHealthInsuranceVM VM => Service;
    private EditContext _editContext;
    private CancellationTokenSource _ct;
    private EventCallback _onOkHandler;

    [Parameter] public string CompanyName { set { VM.Model.Name = value; } }
    [Parameter] public string CompanyAcronym { set { VM.Model.Acronym = value; } }


    [Parameter] public EventCallback OnSuccess { get; set; }
    [Parameter] public EventCallback<string> OnError { get; set; }
    [Parameter] public EventCallback OnCancel { get; set; }

    private Action _onAdded;
    private Action _onError;
    private Action _onWarning;
    private Action _onMessage;

    protected override void OnInitialized()
    {
        _editContext = new EditContext(VM.Model);

        _onError = () => ShowNotification("Error", 
            VM.InformationMessage, 
            ModalType.MessageError,
            EventCallback.Factory.Create(this, OnCloseModal));

        _onWarning = () => ShowNotification("Advertencia", 
            VM.InformationMessage, 
            ModalType.MessageWarning,
            EventCallback.Factory.Create(this, OnCloseModal));

        _onMessage=()=> ShowNotification("Notificación",
            VM.InformationMessage,
            ModalType.MessageError,
            EventCallback.Factory.Create(this, OnCloseModal));

        //VM.OnShowConcurrencyError += () => _ = OnError.InvokeAsync(VM.InformationMessage);

        VM.OnHealthInsuranceAdded += OnSaved;
        VM.OnShowError += _onError;
        VM.OnShowWarning += _onWarning;
        VM.OnShowMessage += _onMessage;
    }
    private void ShowNotification(string title, string message, ModalType type, EventCallback onOkHandler)
    {
        ModalTitle = title;
        ModalType = type;
        ModalMessage = message;
        ModalVisible = true;
        _onOkHandler = onOkHandler;

        StateHasChanged();
    }
    public async Task SaveAsync()
    {
        if (Validate())
        {
            _ct?.Dispose();
            _ct = new CancellationTokenSource();
            await VM.AddHealthCompany(_ct.Token);
        }
    }
    public void OnCancelSave()
    {
        _ = OnCancel.InvokeAsync();
    }
    public void OnSaved()
    {
        ShowOk = true;
        ShowCancel = false;
        ShowNotification("Éxito", VM.InformationMessage, ModalType.MessageSuccess, EventCallback.Factory.Create(this, OnCloseModal));

    }
    public void OnCloseModal()
    {
        ShowOk = false;
        ShowCancel = true;
        ModalVisible = false;
        _ = OnSuccess.InvokeAsync();
        StateHasChanged();
    }
    public void CleanField()
    {
        VM.Model.Name = string.Empty;
        VM.Model.Acronym = string.Empty;
        VM.Model.InformationMessage = string.Empty;

        // Opcional: resetea el estado de validación visual
        _editContext?.MarkAsUnmodified();
    }
    public void Dispose()
    {
        CleanField();
        if (VM is not null)
        {
            VM.OnHealthInsuranceAdded -= OnSaved;
            VM.OnShowError -= _onError;
            VM.OnShowWarning -= _onWarning;
            VM.OnShowMessage -= _onMessage;
        }
        _ct?.Dispose();
    }
}