//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.CommonComponents.Views;
using MedRec.HealthInsurance.ViewModels.VM;
using MedRec.HealthInsurance.Views.Resources;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;

namespace MedRec.HealthInsurance.Views.Components;
public partial class AddHealthInsuranceComponent : IDisposable
{
    public bool Validate() => _editContext.Validate();
    private CreateHealthInsuranceVM VM => Service;
    private EditContext _editContext;
    private bool _showModal;
    private bool isLoading = false;
    private CancellationTokenSource _ct;

    [Parameter] public string CompanyName { set { VM.Model.Name = value; } }
    [Parameter] public string CompanyAcronym { set { VM.Model.Acronym = value; } }
    [Parameter] public EventCallback OnHealthInsuranceCreated { get; set; }
    [Parameter] public EventCallback OnCancelAdd { get; set; }
    protected override void OnInitialized()
    {
        try
        {
            _editContext = new EditContext(VM.Model);
            VM.OnHealthInsuranceAdded += ShowSuccessModal;
        }
        catch (Exception)
        {
            VM.OnHealthInsuranceAdded -= ShowSuccessModal;
        }

    }
    private void OnAccept()
    {
        ModalVisibleB = false;
        OnHealthInsuranceCreated.InvokeAsync(); 
    }
    public void Dispose()
    {
        CleanField();
        VM.OnHealthInsuranceAdded -= ShowSuccessModal;
    }
    private void ShowSuccessModal()
    {
        ModalType = ModalType.MessageSuccess;
        ModalTitle = "Operación exitosa";

        ModalMessage= AddHealthInsuranceMessages.SuccessfulAddedMessage;
        ModalVisibleB = true;
    }

    public async Task SaveAsync()
    {
        if (Validate())
        {
            _ct?.Dispose();
            _ct = new CancellationTokenSource();
            await VM.AddHealthCompany(_ct.Token);
            // Notificamos que se actualizó
            //await OnHealthInsuranceCreated.InvokeAsync();
        }
    }
    public void CleanField()
    {
        VM.Model.Name = string.Empty;
        VM.Model.Acronym = string.Empty;
        VM.Model.InformationMessage = string.Empty;

        // Opcional: resetea el estado de validación visual
        _editContext?.MarkAsUnmodified();
    }
    //private void CancelAdd()
    //{
    //    ClearForm();
    //    VM.InformationMessage = string.Empty;
    //    VM.OnHealthInsuranceAdded -= ShowSuccessModal;
    //    OnCancelAdd.InvokeAsync();
    //}

}