//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.CommonComponents.Views;
using MedRec.HealthInsurance.ViewModels.VM;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;

namespace MedRec.HealthInsurance.Views.Components;
public partial class AddHealthInsuranceComponent : IDisposable
{
    private CreateHealthInsuranceVM VM => Service;
    private EditContext EditContext;
    private bool _showModal;

    [Parameter] public string CompanyName { set { VM.Model.Name = value; } }
    [Parameter] public string CompanyAcronym { set { VM.Model.Acronym = value; } }
    [Parameter] public EventCallback OnAddedCompany { get; set; }
    [Parameter] public EventCallback OnCancelAdd { get; set; }
    protected override void OnInitialized()
    {
        try
        {
            EditContext = new EditContext(VM.Model);
            VM.OnHealthInsuranceAdded += ShowSuccessModal;
        }
        catch (Exception)
        {
            VM.OnHealthInsuranceAdded -= ShowSuccessModal;
        }

    }

    private void OnAccept()
    {
        _showModal = false;
        _ = Dispose();
    }
    public async Task Dispose()
    {
        ClearForm();
        await OnAddedCompany.InvokeAsync();
        VM.OnHealthInsuranceAdded -= ShowSuccessModal;
    }
    private void ShowSuccessModal()
    {
        _showModal = true;
    }

    private async Task AddHealthCompany()
    {

        await VM.AddHealthCompany();

    }
    private void ClearForm()
    {
        CompanyName = string.Empty;
        CompanyAcronym = string.Empty;
    }
    private void CancelAdd()
    {
        ClearForm();
        VM.InformationMessage = string.Empty;
        VM.OnHealthInsuranceAdded -= ShowSuccessModal;
        OnCancelAdd.InvokeAsync();
    }

}