//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace MedRec.HealthInsurance.Views.Components;
public partial class HealthInsuranceSelector
{
    [Parameter] public EventCallback<(Guid Id, string Name)> OnSelected { get; set; }

    // Referencias a subcomponentes
    private AddHealthInsuranceComponent? _addRef;
    private UpdateHealthInsuranceComponent? _updateRef;

    // Estados
    private bool _showList;
    private bool _showAdd;
    private bool _showUpdate;
    private Guid? _updateId;

    // === API pública ===
    public void Open()
    {
        _showList = true;
        StateHasChanged();
    }

    public void CloseAll()
    {
        _showList = false;
        _showAdd = false;
        _showUpdate = false;
        _updateId = null;
        StateHasChanged();
    }

    // === RenderFragments ===
    private RenderFragment ListModalBody => builder =>
    {
        builder.OpenComponent<HealthInsuranceComponent>(0);
        builder.AddAttribute(1, nameof(HealthInsuranceComponent.MaxPageButton), 3);
        builder.AddAttribute(2, nameof(HealthInsuranceComponent.OnHealthCompanySelected),
            EventCallback.Factory.Create<(Guid, string)>(this, OnHealthCompanySelectedInternal));
        builder.AddAttribute(3, nameof(HealthInsuranceComponent.OnRequestAddHealthInsurance),
            EventCallback.Factory.Create(this, () =>
            {
                _showList = false;
                _showAdd = true;
            }));
        builder.AddAttribute(4, nameof(HealthInsuranceComponent.OnRequestUpdateHealthInsurance),
            EventCallback.Factory.Create<Guid>(this, id =>
            {
                _updateId = id;
                _showList = false;
                _showUpdate = true;
            }));
        builder.CloseComponent();
    };

    private RenderFragment AddModalBody => builder =>
    {
        builder.OpenComponent<AddHealthInsuranceComponent>(0);
        builder.AddAttribute(1, nameof(AddHealthInsuranceComponent.OnSuccess),
            EventCallback.Factory.Create(this, OnAddSuccess));
        builder.AddAttribute(2, nameof(AddHealthInsuranceComponent.OnError),
            EventCallback.Factory.Create<string>(this, OnAddError));
        builder.AddAttribute(3, nameof(AddHealthInsuranceComponent.OnCancel),
            EventCallback.Factory.Create(this, OnAddCancel));
        builder.AddComponentReferenceCapture(4, inst => _addRef = (AddHealthInsuranceComponent?)inst);
        builder.CloseComponent();
    };

    private RenderFragment UpdateModalBody => builder =>
    {
        if (_updateId.HasValue)
        {
            builder.OpenComponent<UpdateHealthInsuranceComponent>(0);
            builder.AddAttribute(1, nameof(UpdateHealthInsuranceComponent.HealthInsuranceId), _updateId.Value);
            builder.AddAttribute(2, nameof(UpdateHealthInsuranceComponent.OnSuccess),
                EventCallback.Factory.Create(this, OnUpdateSuccess));
            builder.AddAttribute(3, nameof(UpdateHealthInsuranceComponent.OnError),
                EventCallback.Factory.Create<string>(this, OnUpdateError));
            builder.AddAttribute(4, nameof(UpdateHealthInsuranceComponent.OnCancel),
                EventCallback.Factory.Create(this, OnUpdateCancel));
            builder.AddComponentReferenceCapture(5, inst => _updateRef = (UpdateHealthInsuranceComponent?)inst);
            builder.CloseComponent();
        }
    };

    // === Handlers internos ===
    private async Task OnHealthCompanySelectedInternal((Guid Id, string Name) selected)
    {
        CloseAll();
        if (OnSelected.HasDelegate)
            await OnSelected.InvokeAsync(selected);
    }

    private async Task OnAddSuccess()
    {
        _showAdd = false;
        await Task.Delay(100);
        _showList = true;
    }

    private async Task OnAddCancel()
    {
        _showAdd = false;
        await Task.Delay(100);
        _showList = true;
    }

    private async Task OnAddError(string message)
    {
        _showAdd = false;
        await Task.Delay(100);
        _showList = true;
    }

    private async Task OnUpdateSuccess()
    {
        _updateId = null;
        _showUpdate = false;
        await Task.Delay(100);
        _showList = true;
    }

    private async Task OnUpdateCancel()
    {
        _updateId = null;
        _showUpdate = false;
        await Task.Delay(100);
        _showList = true;
    }

    private async Task OnUpdateError(string message)
    {
        _updateId = null;
        _showUpdate = false;
        await Task.Delay(100);
        _showList = true;
    }
}