//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.Entity.DTOs;
using MedRec.HealthInsurance.ViewModels.VM;
using MedRec.HealthInsurance.Views.Resources;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace MedRec.HealthInsurance.Views.Components;
public partial class HealthInsuranceComponent
{
    private CancellationTokenSource _cts;
    [Inject] public NavigationManager NavigationManager { get; set; }
    [Parameter] public HealthInsuranceCatalogVM Model { get; set; }
    [Inject] public HealthInsuranceCatalogVM DefaultModel { get; set; }
    [Parameter] public EventCallback<(Guid Id, string Name)> OnHealthCompanySelected { get; set; }
    [Parameter] public EventCallback<string> FooterMessageParameterChanged { get; set; }
    [Parameter] public int MaxPageButton { get; set; }

    [Parameter]
    public string FooterMessage
    {
        get => _footerMessage;
        set
        {
            if (_footerMessage != value)
            {
                _footerMessage = value;
                FooterMessageParameterChanged.InvokeAsync(value);
            }
        }
    }

    private PaginationDto _paginationDto = new(1, 10);
    private int _totalPages = 1;

    private string _footerMessage = "";
    private bool showHealthCompanyAdd;
    private bool showHealthCompanyDelete;
    private bool showHealthCompanyUpdate;
    private Guid healthCompanyId;

    protected override async Task OnInitializedAsync()
    {
        if (Model == null)
        {
            Model = DefaultModel;
        }
        await LoadHealthCompanies();
    }
    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
    }
    private async void OnSearchTermChanged(ChangeEventArgs e)
    {
        _paginationDto.Filter = e.Value.ToString();
        _paginationDto.CurrentPage = 1;
        await LoadHealthCompanies();
    }
    private async Task SelectHealthInsurance(Guid healthCompanyId, string name)
    {
        await OnHealthCompanySelected.InvokeAsync((healthCompanyId, name));
    }
    private async Task LoadHealthCompanies()
    {
        _cts?.Dispose();
        _cts = new CancellationTokenSource();

        await Model.LoadHealthCompaniesAsync(_paginationDto, _cts.Token);
        var total = Model.TotalRecords;
        FooterMessage = string.Format(HealthInsuranceMessages.TotalRegistryTemplate, total);
        _totalPages = (int)Math.Ceiling((double)total / _paginationDto.PageSize);
        StateHasChanged();  // Forzar la actualización del componente
    }
    private async Task HandlePageChanged(int newPage)
    {
        _paginationDto.CurrentPage = newPage;
        await LoadHealthCompanies();
    }
    //{healthCompanyId}
    private void OnUpdateHealthInsurance(Guid healthCompanyId)
    {
        showHealthCompanyUpdate = true;
        this.healthCompanyId = healthCompanyId;
    }
    private void OnDeleteHealthInsurance(Guid healthCompanyId)
    {
        showHealthCompanyDelete = true;
        this.healthCompanyId = healthCompanyId;
    }
    private async Task OnAcceptDelete()
    {
        // await Model.DeleteHealthCompanyAsync(healthCompanyId);
        showHealthCompanyDelete = false;
        await LoadHealthCompanies();
    }
    private void OnAddHealthCompany(MouseEventArgs e)
    {
        showHealthCompanyAdd = true;
    }

    private void OnCloseHealthCompanyUpdate(bool state)
    {
        showHealthCompanyUpdate = state;
    }
    private void OnCloseHealthCompanyAdd(bool state)
    {
        showHealthCompanyAdd = state;

    }

    private void OnCloseHealthCompanyDelete(bool state)
    {
        showHealthCompanyDelete = state;
    }

    private async Task OnAddedCompany()
    {
        await OnCancelAdder();
    }
    private async Task OnCancelAdder()
    {
        await LoadHealthCompanies();
        showHealthCompanyAdd = false;
    }
    private async Task OnHealthCompanyUpdated()
    {
        await LoadHealthCompanies();
        showHealthCompanyUpdate = false;
    }
}