//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.CommonComponents.Views;
using MedRec.Entity.DTOs;
using MedRec.HealthInsurance.ViewModels.Models;
using MedRec.HealthInsurance.ViewModels.VM;
using MedRec.HealthInsurance.Views.Pages;
using MedRec.HealthInsurance.Views.Resources;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace MedRec.HealthInsurance.Views.Components;
public partial class HealthInsuranceComponent
{
    private CancellationTokenSource _cts;
    private CancellationTokenSource _debounceCts;
    [Inject] public NavigationManager NavigationManager { get; set; }
    private HealthInsuranceCatalogVM VM => Service;
    [Parameter] public EventCallback<(Guid Id, string Name)> OnHealthCompanySelected { get; set; }
    [Parameter] public EventCallback<string> FooterMessageParameterChanged { get; set; }
    [Parameter] public int MaxPageButton { get; set; }

    [Parameter]
    public string FooterMessage
    {
        get => _footerMessage;
        set
        {
            if (_footerMessage != value)
            {
                _footerMessage = value;
                FooterMessageParameterChanged.InvokeAsync(value);
            }
        }
    }
    private string Filter
    {
        get => _paginationDto.FilterOne;
        set
        {
            if (_paginationDto.FilterOne != value)
            {
                _paginationDto.FilterOne = value;
                // Llamar al método de debounce cada vez que el valor cambia
                _ = OnSearchTermChanged(value);
            }
        }
    }

    private PaginationDto _paginationDto = new(1, 10);
    private int _totalPages = 1;

    // Estado de navegación
    private bool _navigateAfterClose = false;
    private string _navigationUrl = "/";

    // Visibilidad y contenido del modal
    private bool _showModal;
    private string _modalTitle = "MENSAJE DEL SISTEMA";
    private string _footerMessage = string.Empty;
    private EventCallback _onAcceptCallback;

    // Comportamiento y estilo del modal
    private ModalType _modalType = ModalType.MessageInfo;
    private bool _centerText;
    private bool _actionDangerous;

    // Configuración de botones
    private bool _showAcceptButton;
    private bool _showCancelButton;
    private string _buttonAcceptText;
    private string _buttonCancelText;

    private Guid healthCompanyId;
    private bool _addAction;
    private bool _deleteAction;
    private bool _updateAction;

    protected override async Task OnInitializedAsync()
    {
        VM.OnShowMessage += () => ShowModalMessage(title: "Información", 
                                                   type: ModalType.MessageInfo, 
                                                   onAccept: default, 
                                                   showAcceptButton: false, 
                                                   buttonCancelTex: "SALIR");

        VM.OnShowWarning += () => ShowModalMessage(title: "Advertencia", 
                                                   type: ModalType.MessageWarning, 
                                                   onAccept: default,
                                                   showAcceptButton: false,
                                                   buttonCancelTex: "SALIR");

        VM.OnShowError += () => ShowModalMessage(title: "Error",
                                                 type: ModalType.MessageError, 
                                                 onAccept: default,
                                                 showAcceptButton:false,
                                                 buttonCancelTex:"SALIR");

        VM.OnShowConcurrencyError += () => ShowModalMessage(title: "Conflicto de concurrencia",     
                                                            type: ModalType.MessageError, 
                                                            onAccept: default,
                                                            showAcceptButton: false,
                                                            buttonCancelTex: "SALIR");
        VM.OnHealthInsuranceDeleted += StateHasChanged;

        await LoadHealthCompanies();
    }
    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
    }
    private void ShowModalMessageAndNavigate(string title, ModalType type, string navigationUrl)
    {
        _modalTitle = title;
        _modalType = type;
        _showModal = true;
        _navigateAfterClose = true;
        _navigationUrl = navigationUrl;
        InvokeAsync(StateHasChanged);
    }
    private void ShowModalMessage(string title,
        ModalType type, EventCallback onAccept, bool centerText = true,
        bool actionDangerous = false, bool showAcceptButton = true,
        bool showCancelButton = true, string buttonAcceptText = "ACEPTAR",
        string buttonCancelTex = "CANCELAR")
    {
        _modalTitle = title;
        _modalType = type;
        _onAcceptCallback = onAccept;
        _centerText = centerText;
        _actionDangerous = actionDangerous;
        _showAcceptButton = showAcceptButton;
        _showCancelButton = showCancelButton;
        _buttonAcceptText = buttonAcceptText;
        _buttonCancelText = buttonCancelTex;
        _showModal = true;
        _navigateAfterClose = false;
        InvokeAsync(StateHasChanged);
    }
    private async Task OnSearchTermChanged(string searchTerm)
    {
        // Cancelar la búsqueda anterior si existe
        _debounceCts?.Cancel();
        _debounceCts = new CancellationTokenSource();

        // Solo buscar si hay más de 2 caracteres o está vacío
        if (searchTerm.Length > 2 || searchTerm.Length == 0)
        {
            try
            {
                // Esperar 600ms antes de buscar
                await Task.Delay(600, _debounceCts.Token);
                _paginationDto.CurrentPage = 1;
                await LoadHealthCompanies();
            }
            catch (TaskCanceledException)
            {
                // Ignorar si se cancela por nueva entrada
            }
        }
    }
    private async Task SelectHealthInsurance(HealthInsuranceModel healthInsurance)
    {
        await OnHealthCompanySelected.InvokeAsync((healthInsurance.Id, healthInsurance.Name));
    }
    private async Task LoadHealthCompanies()
    {
        _cts?.Dispose();
        _cts = new CancellationTokenSource();

        await VM.GetHealthInsuranceAsync(_paginationDto, _cts.Token);
        var total = VM.TotalRecords;
        FooterMessage = string.Format(HealthInsuranceMessages.TotalRegistryTemplate, total);
        _totalPages = (int)Math.Ceiling((double)total / _paginationDto.PageSize);
        StateHasChanged();  // Forzar la actualización del componente
    }
    private async Task HandlePageChanged(int newPage)
    {
        _paginationDto.CurrentPage = newPage;
        await LoadHealthCompanies();
    }
    //{healthCompanyId}

    private void OnAddHealthInsurance()
    {
        _addAction = true;
        ShowModalMessage(
            title: AddHealthInsuranceMessages.TitleText,
            type: ModalType.NormalContent,
            onAccept: EventCallback.Factory.Create(this, OnAddedCompany),
            centerText: false,
            showAcceptButton: false);
    }
    private void OnUpdateHealthInsurance(HealthInsuranceModel healthCompany)
    {
        _updateAction = true;
        ShowModalMessage(
            title:UpdateHealthInsuranceMessages.TitleText,
            type: ModalType.NormalContent,
            onAccept: EventCallback.Factory.Create(this, OnHealthCompanyUpdated), 
            centerText: false,
            showAcceptButton: false,
            showCancelButton: false);
        this.healthCompanyId = healthCompany.Id;
    }
    private void OnDeleteHealthInsurance(HealthInsuranceModel healthCompany)
    {
        _deleteAction = true;

        VM.InformationMessage = HealthInsuranceMessages.ModalMessageText;
        ShowModalMessage(HealthInsuranceMessages.ModalTitleText,
            ModalType.MessageWarning,
            onAccept: EventCallback.Factory.Create(this, OnAcceptDelete),
            true, true, true, true, "SI", "NO");
        this.healthCompanyId = healthCompany.Id;
    }
    private async Task OnAcceptDelete()
    {   
        _showModal = false;
        await VM.DeleteHealthInsuranceAsync(healthCompanyId);       
        await LoadHealthCompanies();
    }


    public void OnCloseModal(bool state)
    {
        _addAction = false;
        _updateAction = false;
        _deleteAction = false;
        _showModal = state;
    }

    private async Task OnAddedCompany()
    {
        _addAction = false;
        await LoadHealthCompanies();
        _showModal = false;

    }
    private async Task OnHealthCompanyUpdated()
    {
        _updateAction = false;
        await LoadHealthCompanies();
        _showModal = false;
    }
    private void OnCancelAdder()
    { _showModal = false; }

    public void Dispose()
    {
        if (VM is not null)
        {
            VM.OnShowMessage -= () => ShowModalMessage("Información", ModalType.MessageInfo, default);
            VM.OnShowWarning -= () => ShowModalMessage("Advertencia", ModalType.MessageWarning, default);
            VM.OnShowError -= () => ShowModalMessage("Error", ModalType.MessageError, default);
            VM.OnShowConcurrencyError -= () => ShowModalMessage("Conflicto de concurrencia", ModalType.MessageError, default);
            VM.OnHealthInsuranceDeleted -= StateHasChanged;
        }
        _cts?.Dispose();
    }
}