//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.HealthInsurance.ViewModels.VM;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using System.Threading.Tasks;

namespace MedRec.HealthInsurance.Views.Components;
public partial class UpdateHealthInsuranceComponent
{
    public bool Validate() => _editContext.Validate();
    private UpdateHealthInsuranceVM VM => Service;
    private EditContext _editContext;
    //private bool showModal;
    private CancellationTokenSource _ct;
    [Parameter] public EventCallback OnHealthInsuranceUpdated { get; set; }
    [Parameter] public Guid HealthInsuranceId { get; set; }

    protected override async Task OnInitializedAsync()
    {
        _ct?.Dispose();
        _ct = new CancellationTokenSource();

        _editContext = new EditContext(VM.Model);

        await VM.GetHealthInsuranceAsync(HealthInsuranceId, _ct.Token);

    }

    public async Task SaveAsync()
    {
        if (Validate())
        {
            _ct?.Dispose();
            _ct = new CancellationTokenSource();
            await VM.UpdateHealthCompany(_ct.Token);
            // Notificamos que se actualizó
            await OnHealthInsuranceUpdated.InvokeAsync();
        }
    }

    public void CleanField()
    {
        VM.Model.Name = string.Empty;
        VM.Model.Acronym = string.Empty;
        VM.Model.InformationMessage = string.Empty;

        // Opcional: resetea el estado de validación visual
        _editContext?.MarkAsUnmodified();
    }
}