<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedRec.Professionals.ViewModels\MedRec.Professionals.ViewModels.csproj" />
    <ProjectReference Include="..\MedRec.Identity.Views\MedRec.Identity.Views.csproj" />
  </ItemGroup>

</Project>
