//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRec.Patients.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreatePatientMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatePatientMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedRec.Patients.Views.Resources.CreatePatientMessages", typeof(CreatePatientMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVO PACIENTE.
        /// </summary>
        internal static string AddPatientMenuItemTitle {
            get {
                return ResourceManager.GetString("AddPatientMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTA DE PACIENTE.
        /// </summary>
        internal static string AddPatientPageTitle {
            get {
                return ResourceManager.GetString("AddPatientPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PACIENTE {0} CREADO.
        /// </summary>
        internal static string AddPatientTemplate {
            get {
                return ResourceManager.GetString("AddPatientTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} AÑOS, {1} MESES.
        /// </summary>
        internal static string AgeOfPatientTemplate {
            get {
                return ResourceManager.GetString("AgeOfPatientTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA DE NACIMIENTO.
        /// </summary>
        internal static string DateOfBirthLabel {
            get {
                return ResourceManager.GetString("DateOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUMERO DE DOCUMENTO.
        /// </summary>
        internal static string DocumentNumberLabel {
            get {
                return ResourceManager.GetString("DocumentNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN DE CORREO ELECTRONICO.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE DEL PACIENTE.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUMERO DE TARJETA.
        /// </summary>
        internal static string InsuranceHealthCardLabel {
            get {
                return ResourceManager.GetString("InsuranceHealthCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBRA SOCIAL / PREPAGA.
        /// </summary>
        internal static string InsuranceHealthCompanyLabel {
            get {
                return ResourceManager.GetString("InsuranceHealthCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUMERO DE SOCIO.
        /// </summary>
        internal static string InsuranceHealthMemberNumberLabel {
            get {
                return ResourceManager.GetString("InsuranceHealthMemberNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAN DE COBERTURA.
        /// </summary>
        internal static string InsuranceHealthPlanLabel {
            get {
                return ResourceManager.GetString("InsuranceHealthPlanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APELLIDO DEL PACIENTE.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PACIENTE AGREGADO SATISFACTORIAMENTE.
        /// </summary>
        internal static string PatientAddedMessage {
            get {
                return ResourceManager.GetString("PatientAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUMERO DE TELEFONO.
        /// </summary>
        internal static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
    }
}
