//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRec.Patients.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListPatientsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListPatientsMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedRec.Patients.Views.Resources.ListPatientsMessages", typeof(ListPatientsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EL PACIENTE {0} FUE ELIMINADO CON EXITO.
        /// </summary>
        internal static string DeletedPatientMessageTemplate {
            get {
                return ResourceManager.GetString("DeletedPatientMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR AL ELIMINAR EL PACIENTE {0}.
        /// </summary>
        internal static string ErrorDeletePatientMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorDeletePatientMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR PACIENTE.
        /// </summary>
        internal static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACCIONES.
        /// </summary>
        internal static string HeadActionsText {
            get {
                return ResourceManager.GetString("HeadActionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA NACIMIENTO.
        /// </summary>
        internal static string HeadDateOfBirthText {
            get {
                return ResourceManager.GetString("HeadDateOfBirthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D.N.I..
        /// </summary>
        internal static string HeadDocumentNumberText {
            get {
                return ResourceManager.GetString("HeadDocumentNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string HeadIdText {
            get {
                return ResourceManager.GetString("HeadIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APELLIDO.
        /// </summary>
        internal static string HeadLastNameText {
            get {
                return ResourceManager.GetString("HeadLastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE.
        /// </summary>
        internal static string HeadNameText {
            get {
                return ResourceManager.GetString("HeadNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TELÉFONO.
        /// </summary>
        internal static string HeadPhoneText {
            get {
                return ResourceManager.GetString("HeadPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ESTA SEGURO DE ELIMINAR AL PACIENTE?.
        /// </summary>
        internal static string ModalMessageText {
            get {
                return ResourceManager.GetString("ModalMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}.
        /// </summary>
        internal static string ModalMessageTextTemplate {
            get {
                return ResourceManager.GetString("ModalMessageTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a POCESO DE ELIMINACIÓN.
        /// </summary>
        internal static string ModalTitleText {
            get {
                return ResourceManager.GetString("ModalTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGRESE EL NOMBRE DEL PACIENTE O EL DNI SIN PUNTOS PARA FILTRAR.
        /// </summary>
        internal static string PlaceholderFilterInput {
            get {
                return ResourceManager.GetString("PlaceholderFilterInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR.
        /// </summary>
        internal static string RecoberButton {
            get {
                return ResourceManager.GetString("RecoberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO SE ENCONTRARON PACIENTES.
        /// </summary>
        internal static string ThereAreNoPatientsMessage {
            get {
                return ResourceManager.GetString("ThereAreNoPatientsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LISTADO DE PACIENTES.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR PACIENTE.
        /// </summary>
        internal static string ToolTipDeletButtonMessage {
            get {
                return ResourceManager.GetString("ToolTipDeletButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITAR PACIENTE.
        /// </summary>
        internal static string ToolTipEditButtonMessage {
            get {
                return ResourceManager.GetString("ToolTipEditButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL DE PACIENTES: {0}.
        /// </summary>
        internal static string TotalPatientMessageTemplate {
            get {
                return ResourceManager.GetString("TotalPatientMessageTemplate", resourceCulture);
            }
        }
    }
}
