<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\2.ApplicationBusinessObjects\MedRec.HealthInsurance.UeseCases\MedRec.HealthInsurance.UseCases.csproj" />
    <ProjectReference Include="..\..\2.ApplicationBusinessObjects\MedRec.MedicalAppointments.UseCases\MedRec.MedicalAppointments.UseCases.csproj" />
    <ProjectReference Include="..\..\2.ApplicationBusinessObjects\MedRec.MedicalVisit.UseCases\MedRec.MedicalVisit.UseCases.csproj" />
    <ProjectReference Include="..\..\2.ApplicationBusinessObjects\MedRec.Patients.UseCases\MedRec.Patients.UseCases.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.HealthInsurance.Presenters\MedRec.HealthInsurance.Presenters.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.HealthInsurance.ViewModels\MedRec.HealthInsurance.ViewModels.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.MedicalAppointments.Presenters\MedRec.MedicalAppointments.Presenters.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.MedicalAppointments.ViewModels\MedRec.MedicalAppointments.ViewModels.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.MedicalVisit.Presenters\MedRec.MedicalVisit.Presenters.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.MedicalVisit.ViewModels\MedRec.MedicalVisit.ViewModels.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.Patients.Presenters\MedRec.Patients.Presenters.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\MedRec.Patients.ViewModels\MedRec.Patients.ViewModels.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\Presenters\MedRec.DynamicTemplates.Presenters\MedRec.DynamicTemplates.Presenters.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\Repositories\MedRec.DynamicTemplates.Repositories\MedRec.DynamicTemplates.Repositories.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\Repositories\MedRec.MedicalVisit.Repositories\MedRec.MedicalVisit.Repositories.csproj" />
    <ProjectReference Include="..\..\3.InterfaceAdapters\Repositories\MedRec.Repositories\MedRec.Repositories.csproj" />
    <ProjectReference Include="..\MedRec.DynamicTemplates.DataContext.MySql\MedRec.DynamicTemplates.DataContext.MySql.csproj" />
    <ProjectReference Include="..\MedRec.HealthInsurance.DataContext.EF\MedRec.HealthInsurance.DataContext.EF.csproj" />
    <ProjectReference Include="..\MedRec.MedicalAppointment.DataContext.MySql\MedRec.MedicalAppointments.DataContext.MySql.csproj" />
    <ProjectReference Include="..\MedRec.MedicalVisit.DataContext.MySql\MedRec.MedicalVisit.DataContext.MySql.csproj" />
    <ProjectReference Include="..\MedRec.Patients.DataContext.MySql\MedRec.Patients.DataContext.MySql.csproj" />
  </ItemGroup>

</Project>
