//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MedRec.Entity.Extensions;
using MedRec.MedicalVisit.ViewModels.VM;
using MedRec.MedicalVisit.Views.Resources;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace MedRec.MedicalVisit.Views.Pages;
public partial class UpdateMedicalVisitPage
{
    private UpdateMedicalVisitVMOrchestrator VM => Service;

    [Parameter] public Guid? VisitId { get; set; }
    [Parameter] public Guid PatientId { get; set; }

    private string footerMessage;
    private bool IsEditMode => VisitId.HasValue;
    private bool IsReadOnly { get; set; }
    private string Title { get; set; }
    private bool _cloneNow = false;
    CancellationTokenSource ct = new CancellationTokenSource();
    protected override async Task OnInitializedAsync()
    {
        ct?.Dispose();
        ct = new CancellationTokenSource();

        await VM.LoadDataPatient(PatientId, ct.Token);
        // Modo Vista: Cargar datos de la visita existente
        await VM.LoadVisitAsync(VisitId.Value);
        _cloneNow = true;

        base.OnInitialized();
    }

    // Función auxiliar para leer los valores de la Query String

    protected override async Task OnParametersSetAsync()
    {

        await Task.Yield();

        if (IsEditMode && VisitId.HasValue)
        {
            IsReadOnly = true;
            Title = $"{VM.Model.FullName} | EDAD {VM.Model.DateOfBirth.CalculateAge()} AÑOS | Fecha de visita {VM.Model.VisitDate:dd/MM/yyyy}";

        }
        else
        {
            Title = string.Format(MedicalVisitMessages.CreateMedicalVisitTitleTemplate, VM.Model.FullName, VM.Model.DateOfBirth.CalculateAge());
        }
    }
    private void OnMessageFooterChange(string title)
    {
        footerMessage = title;
    }
    ErrorBoundary ErrorBoundaryRef;

    void Recover()
    {
        ErrorBoundaryRef?.Recover();
    }
}