//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;

namespace MedRec.CommonComponents.Views.Exceptions;
public partial class ExceptionDisplayComponent
{
    [Parameter]
    public Exception Exception { get; set; }
}