//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;

namespace MedRec_PatientMedicalVisit.Views.Components;
//public partial class PatientMedicalVisit
//{

//    [Parameter] public int MedicalHistoryId { get; set; }

//    public bool showModal = false;
//    protected override async Task OnInitializedAsync()
//    {
//        await ViewModel.GetLaboratoryResultTypes();
//        ViewModel.MedicalHistoryId = MedicalHistoryId;
//        ViewModel.OnMedicalVisitAdded += ShowSuccessModal;
//    }
//    protected override async void OnAfterRender(bool firstRender)
//    {
//        if (firstRender)
//        {
//            await ToggleSection();
//        }
//    }
//    private async Task HandleValidSubmit()
//    {
//        await ViewModel.AddMedicalVisit();
//    }
//    private async Task ToggleSection()
//    {
//        await JS.InvokeVoidAsync("toggleResultSection");
//    }
//    private void SetResultSelection(PatientLaboratoryResultViewModel result)
//    {
//        if (result.IsSelected)
//        {
//            var itemSelect = ViewModel.PatientLaboratoryResults
//                .FirstOrDefault(x => x.ResultTypeId == result.ResultTypeId);
//            if (itemSelect == null)
//            {
//                ViewModel.PatientLaboratoryResults.Add(result);
//            }
//            else
//            {
//                itemSelect.ResultDate = ViewModel.VisitDate;
//                itemSelect.ResultValue = result.ResultValue;
//                itemSelect.ResultNotes = result.ResultNotes;
//                itemSelect.IsDeleted = result.IsDeleted;
//            }

//        }
//        else
//        {
//            // Elimina el resultado de la lista si se deselecciona
//            var itemToRemove = ViewModel.PatientLaboratoryResults
//                .FirstOrDefault(x => x.ResultTypeId == result.ResultTypeId);

//            if (ViewModel.MustBeUpdated)
//            {
//                itemToRemove.IsDeleted = true;
//                StateHasChanged();
//            }
//            else
//            {
//                if (itemToRemove != null)
//                {
//                    ViewModel.PatientLaboratoryResults.Remove(itemToRemove);
//                }
//            }
//            _ = ToggleSection();
//            result.ResultNotes = string.Empty;
//            result.ResultValue = string.Empty;
//        }

//        // Forzamos la actualización del estado del componente
//        StateHasChanged();
//    }

//    private void OnAccept()
//    {
//        showModal = false;
//        ViewModel.Clear();
//        Navigation.NavigateTo("/", true);
//    }
//    private void ShowSuccessModal(string message)
//    {
//        showModal = true;
//        ViewModel.OnMedicalVisitAdded -= ShowSuccessModal;
//    }
//}